services:
  - type: web
    name: telegram-speech-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
